template: |
    ## :books: Changes since last version

    $CHANGES

    ##### :clap: Many thanks to everyone who participated in this release :point_down:
    $CONTRIBUTORS

replacers:
    - search: '/BB-(\d+)/g'
      replace: 'https://tickets.metabrainz.org/browse/BB-$1'
